apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MiletoCarmelo/DEVOPS_ARGOCD.git
    targetRevision: HEAD
    path: argocd-components
    helm:
      valueFiles:
      #- values-dev.yaml    # Mettons dev en premier
      - values-prod.yaml   # Puis prod
      # - values-tooling.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true