{{- range .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/managed-by: argocd.argoproj.io
    app.kubernetes.io/instance: {{ .name }}
spec:
  encryptedData:
{{- if .encryptedData }}
    {{ toYaml .encryptedData | nindent 4 }}
{{- else }}
    {{ .key }}: {{ .value }}
{{- end }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ .namespace }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
        managed-by: argocd.argoproj.io
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/managed-by: argocd.argoproj.io
        app.kubernetes.io/instance: {{ .name }}
    type: {{ .type | default "Opaque" }}
{{- end }}
