{{- range .Values.secrets }}
---
apiVersion: v1
data:
{{- if .data }}
    {{- toYaml .data | nindent 2 }}
{{- else }}
    {{ .key }}: {{ .value }}
{{- end }}
kind: Secret
metadata:
  name: {{ .name }}
  namespace:  {{ .namespace }}
type: Opaque
{{- end }}
