module: argocd

projects:
  - name: infrastructure  # Ajout du projet infrastructure
  - name: quant-cm

subChartRepositories:
  - name: generic-python-frontend
    project: quant-cm
    url: https://raw.githubusercontent.com/miletocarmelo/DEVOPS_HELM_generic_python_frontend/github-pages

  - name: generic-python-frontend-temp-pod
    project: quant-cm
    url: https://github.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend_temporary_pods_creation/github-pages

apps:
  - name: tsa-prod
    namespace: prod
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis
      helm:
        valueFiles: values.prod.yaml
      targetRevision: prod

  - name: tsa-pod-prod
    namespace: prod
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis-temp-pod
      helm:
        valueFiles: values.prod.yaml
      targetRevision: prod
      
  # Ajout de cert-manager
  - name: cert-manager-setup
    namespace: cert-manager
    project: infrastructure
    source:
      repoURL: "https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git"
      path: "infrastructure/cert-manager"
      targetRevision: HEAD

  # Configuration de l'ingress
  - name: ingress-setup
    namespace: default
    project: quant-cm
    source:
      repoURL: "https://github.com/votre-org/DEVOPS_HELM_localhost_ingress.git"
      path: "ingress-setup"  # Chemin vers votre chart Helm
      targetRevision: HEAD
      helm:
        valueFiles:
          - values-dev.yaml
        # Vous pouvez aussi spécifier des valeurs directement ici si nécessaire
        values: |
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
