module: argocd

projects:
  - name: infrastructure  # Ajout du projet infrastructure
  - name: quant-cm

cert-manager:
  enabled: true
  version: v1.16.1
  url: https://charts.jetstack.io

subChartRepositories:
  - name: generic-python-frontend
    project: quant-cm
    url: https://raw.githubusercontent.com/miletocarmelo/DEVOPS_HELM_generic_python_frontend/github-pages
  
  #   - name: generic-python-frontend-temp-pod
  #     project: quant-cm
  #     url: https://github.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend_temporary_pods_creation/github-pages

apps:

  - name: cert-manager
    namespace: cert-manager
    project: default
    source:
      chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.1
      helm:
        values: |-
          installCRDs: true
          global:
            leaderElection:
              namespace: cert-manager

  - name: tsa-dev # ca va setup le releaseName variabe
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod

  # - name: tsa-pod-dev 
  #   namespace: dev
  #   project: quant-cm
  #   source:
  #     repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
  #     path: umbrella-trading-strategy-analysis-temp-pod
  #     helm:
  #       valueFiles: values.dev.yaml
  #     targetRevision: prod

  - name: ingress-setup-dev     # Changé pour correspondre au nom attendu
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      path: ingress-setup
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod

  - name: success-app-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/success-app.git
      path: "k8s"
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod