module: argocd

projects:
  - name: infrastructure  # Ajout du projet infrastructure
  - name: quant-cm

subChartRepositories:
  - name: generic-python-frontend
    project: quant-cm
    url: https://raw.githubusercontent.com/miletocarmelo/DEVOPS_HELM_generic_python_frontend/github-pages
  
  #   - name: generic-python-frontend-temp-pod
  #     project: quant-cm
  #     url: https://github.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend_temporary_pods_creation/github-pages

apps:
  - name: tsa-dev # ca va setup le releaseName variabe
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod

  # - name: tsa-pod-dev 
  #   namespace: dev
  #   project: quant-cm
  #   source:
  #     repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
  #     path: umbrella-trading-strategy-analysis-temp-pod
  #     helm:
  #       valueFiles: values.dev.yaml
  #     targetRevision: prod

  # Ajout de cert-manager
  - name: cert-manager-setup-dev
    namespace: cert-manager
    project: infrastructure
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      path: infrastructure/cert-manager
      targetRevision: prod

  - name: ingress-setup-dev     # Changé pour correspondre au nom attendu
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/votre-org/DEVOPS_HELM_localhost_ingress.git
      path: ingress-setup
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod