# Define projects
projects:
  - name: infrastructure
  - name: quant-cm

# Define repository configurations
subChartRepositories:
  - name: generic-python-frontend
    project: quant-cm
    url: https://raw.githubusercontent.com/miletocarmelo/DEVOPS_HELM_generic_python_frontend/github-pages

# Define applications
apps:
#   - name: tailscale
#     namespace: tailscale
#     project: infrastructure
#     source:
#       chart: tailscale-operator
#       repoURL: https://pkgs.tailscale.com/helmcharts
#       targetRevision: 1.76.6
#     helm:
#       values: |
#         operator:
#           oauth:
#             existingClientIDSecret:
#               name: operator-oauth
#               key: client_id
#             existingClientSecretSecret:
#               name: operator-oauth
#               key: client_secret
#         proxy:
#          enabled: true
#          routes:
#            - service: ingress-setup-dev.dev  # Le service de votre ingress dans le namespace dev
#              port: 80
#              hostname: mm.ts.ch  # ou le nom que vous préférez

  - name: httpbin
    namespace: httpbin
    project: infrastructure
    source:
      repoURL: https://github.com/matheusfm/httpbin
      path: httpbin
      targetRevision: latest
      directory:
        recurse: true
        jsonnet: {}

  # Ajoutez la config Tailscale
  - name: tailscale-proxy
    namespace: tailscale
    project: infrastructure
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      path: tailscale-proxy
      targetRevision: prod
      directory:
        recurse: true
        jsonnet: {}

  - name: cert-manager
    namespace: cert-manager
    project: infrastructure
    source:
      chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.1
      helm:
        values: |
          installCRDs: true
          global:
            leaderElection:
              namespace: cert-manager

  - name: sealed-secrets
    namespace: sealed-secrets
    project: infrastructure
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.16.2
      helm:
        values: |
          fullnameOverride: sealed-secrets
          commandArgs:
            - --update-status
            - --allow-namespace-wide
          serviceMonitor:
            enabled: false
          ingress:
            enabled: false
          secretName: "sealed-secrets-key"

  - name: metallb
    namespace: metallb-system
    project: infrastructure
    source:
      chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.7
      helm:
        values: |
          crds:
            enabled: true
          controller:
            enabled: true
          speaker:
            enabled: true

  - name: metallb-config
    namespace: metallb-system
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      path: metallb-config
      targetRevision: prod
      directory:
        recurse: true
        jsonnet: {}

  - name: ingress-nginx
    namespace: ingress-nginx
    project: infrastructure
    source:
      chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.11.3
      helm:
        values: |
          controller:
            publishService:
              enabled: true
            service:
              type: LoadBalancer
              externalTrafficPolicy: Local
            metrics:
              enabled: true
            config:
              use-forwarded-headers: "true"
              use-proxy-protocol: "false"
              proxy-real-ip-cidr: "192.168.68.0/24"  # Ajusté pour votre réseau Minikube

  - name: ingress-setup-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      path: ingress-setup
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod
      
  - name: success-app-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/success-app.git
      path: "k8s"
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod

  - name: tsa-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod

  - name: optionsviz-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_OptionsViz.git
      path: umbrella-optionsviz
      helm:
        valueFiles: values.dev.yaml
      targetRevision: prod