module: argocd

projects:
  - name: quant-cm

repoCredentials:

secrets:

apps:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    project: default
    source:
      repoURL: https://kubernetes.github.io/dashboard/
      chart: kubernetes-dashboard
      targetRevision: 7.3.2

  - name: ingress-setup
    namespace: default
    project: default
    source:
      path: ingress-setup-prod
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      targetRevision: HEAD
      # Si vous avez besoin de configuration Helm spécifique
      helm:
        values: |
          domain: dev.quant-cm.com
          service:
            port: 80
            targetPort: 8080  # Ajustez selon votre application
          ingress:
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
          tls:
            secretName: quant-cm-tls