module: argocd

projects:
  - name: quant-cm

subChartRepositories:
  - name: generic-python-frontend
    project: quant-cm
    url: https://raw.githubusercontent.com/miletocarmelo/DEVOPS_HELM_generic_python_frontend/github-pages
  
  - name: generic-python-frontend-temp-pod
    project: quant-cm
    url: https://github.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend_temporary_pods_creation/github-pages

apps:
  - name: tsa-dev
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis
      helm:
        valueFiles: values.dev.yaml
      targetRevision: main

  - name: tsa-pod-dev 
    namespace: dev
    project: quant-cm
    source:
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_DEPLOY_TradingStrategyAnaylsis.git
      path: umbrella-trading-strategy-analysis-temp-pod
      helm:
        valueFiles: values.dev.yaml
      targetRevision: main

  - name: ingress-setup
    namespace: default
    project: default
    source:
      path: ingress-setup-prod
      repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_localhost_ingress.git
      targetRevision: HEAD
      # Si vous avez besoin de configuration Helm spécifique
      helm:
        values: |
          domain: dev.quant-cm.com
          service:
            port: 80
            targetPort: 8080  # Ajustez selon votre application
          ingress:
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
          tls:
            secretName: quant-cm-tls